// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIUgPCQm1IO6NvuJHMWLb8mFb-wlrnxn4',
    appId: '1:250748973645:web:d6bb108d29da8164d16204',
    messagingSenderId: '250748973645',
    projectId: 'sheikh-eccomerce',
    authDomain: 'sheikh-eccomerce.firebaseapp.com',
    storageBucket: 'sheikh-eccomerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUP_g-Q2WSKxAP30cxXMqiS7hzgumqs4s',
    appId: '1:250748973645:android:ba65f419a3ccebbbd16204',
    messagingSenderId: '250748973645',
    projectId: 'sheikh-eccomerce',
    storageBucket: 'sheikh-eccomerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_SeZ4eO9Il2L8Hk9NG2wzgIWECStL-Rw',
    appId: '1:250748973645:ios:1e66592ccce395e3d16204',
    messagingSenderId: '250748973645',
    projectId: 'sheikh-eccomerce',
    storageBucket: 'sheikh-eccomerce.appspot.com',
    androidClientId: '250748973645-srs5eked66cugm9nn7ldc2hfojqcbt28.apps.googleusercontent.com',
    iosClientId: '250748973645-j7jge5v5q1pg46qicm0omvoh0pj65953.apps.googleusercontent.com',
    iosBundleId: 'com.example.day1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_SeZ4eO9Il2L8Hk9NG2wzgIWECStL-Rw',
    appId: '1:250748973645:ios:1e66592ccce395e3d16204',
    messagingSenderId: '250748973645',
    projectId: 'sheikh-eccomerce',
    storageBucket: 'sheikh-eccomerce.appspot.com',
    androidClientId: '250748973645-srs5eked66cugm9nn7ldc2hfojqcbt28.apps.googleusercontent.com',
    iosClientId: '250748973645-j7jge5v5q1pg46qicm0omvoh0pj65953.apps.googleusercontent.com',
    iosBundleId: 'com.example.day1',
  );
}
